### ISSUE TITLE
Mysql to PostgreSQL table structure conversion failed

### ISSUE THREAD

**Issue by PekopT** [slotix/dbconvert-streams-public#1]
original mysql table structure

```-- auto-generated definition
create table djstripe_dispute
(
    djstripe_id               bigint auto_increment
        primary key,
    id                        varchar(255)                not null,
    livemode                  tinyint(1)                  null,
    created                   datetime(6)                 null,
    metadata                  json                        null,
    description               longtext                    null,
    djstripe_created          datetime(6)                 not null,
    djstripe_updated          datetime(6)                 not null,
    amount                    bigint                      not null,
    currency                  varchar(3)                  not null,
    evidence                  json                        not null,
    evidence_details          json                        not null,
    is_charge_refundable      tinyint(1)                  not null,
    reason                    varchar(25)                 not null,
    status                    varchar(22)                 not null,
    djstripe_owner_account_id varchar(255)                null,
    balance_transaction_id    varchar(255)                null,
    charge_id                 varchar(255)                null,
    payment_intent_id         varchar(255)                null,
    balance_transactions      json default (_utf8mb4'[]') not null,
    constraint id
        unique (id),
    constraint djstripe_dispute_balance_transaction__aa7cb920_fk_djstripe_
        foreign key (balance_transaction_id) references djstripe_balancetransaction (id),
    constraint djstripe_dispute_charge_id_ba680941_fk_djstripe_charge_id
        foreign key (charge_id) references djstripe_charge (id),
    constraint djstripe_dispute_djstripe_owner_accou_8010e2d7_fk_djstripe_
        foreign key (djstripe_owner_account_id) references djstripe_account (id),
    constraint djstripe_dispute_payment_intent_id_dc834ee4_fk_djstripe_
        foreign key (payment_intent_id) references djstripe_paymentintent (id)
);

create index djstripe_dispute_balance_transaction_id_aa7cb920
    on djstripe_dispute (balance_transaction_id);

create index djstripe_dispute_charge_id_ba680941
    on djstripe_dispute (charge_id);

create index djstripe_dispute_djstripe_owner_account_id_8010e2d7
    on djstripe_dispute (djstripe_owner_account_id);

create index djstripe_dispute_payment_intent_id_dc834ee4
    on djstripe_dispute (payment_intent_id);

```

error i'm getting:

```
[2023/10/19 19:26:43] [error] target/subscribe.go:206 ERROR: syntax error at or near "[" (SQLSTATE 42601)DDL:

 CREATE TABLE IF NOT EXISTS "public"."djstripe_dispute" ("djstripe_id" BIGSERIAL PRIMARY KEY  NOT NULL, "id" VARCHAR(255) NOT NULL, "livemode" SMALLINT NULL, "created" TIMESTAMP(6) NULL, "metadata" JSON NULL, "description" TEXT NULL, "djstripe_created" TIMESTAMP(6) NOT NULL, "djstripe_updated" TIMESTAMP(6) NOT NULL, "amount" BIGINT NOT NULL, "currency" VARCHAR(3) NOT NULL, "evidence" JSON NOT NULL, "evidence_details" JSON NOT NULL, "is_charge_refundable" SMALLINT NOT NULL, "reason" VARCHAR(25) NOT NULL, "status" VARCHAR(22) NOT NULL, "djstripe_owner_account_id" VARCHAR(255) NULL, "balance_transaction_id" VARCHAR(255) NULL, "charge_id" VARCHAR(255) NULL, "payment_intent_id" VARCHAR(255) NULL, "balance_transactions" JSON DEFAULT '_utf8mb4\'[]\'' NOT NULL); 

[2023/10/19 19:26:43] [error] target/subscribe.go:69 ERROR: syntax error at or near "[" (SQLSTATE 42601)
```

**Comment by PekopT** [comment]
docker-compose.yaml used ( copied from docs ):

```
version: "3.9"
services:
  dbs-api:
    container_name: api
    image: slotix/dbs-api
    entrypoint:
      - ./dbs-api
      - --nats=nats:4222
      - --source=source-reader:8021
      - --target=target-writer:8022
    ports:
      - 8020:8020
    depends_on:
      - nats

  dbs-source-reader:
    container_name: source-reader
    image: slotix/dbs-source-reader
    entrypoint:
      - ./dbs-source-reader
      - --nats=nats:4222
    ports:
      - 8021:8021
    depends_on:
      - dbs-api

  dbs-target-writer:
    container_name: target-writer
    image: slotix/dbs-target-writer
    entrypoint:
      - ./dbs-target-writer
      - --host=dbs-target-writer:8022  
      - --nats=nats:4222
      - --prometheus=http://prometheus:9090
    ports:
      - 8022:8022
    depends_on:
      - dbs-api


  # dbs-target-writer2:
  #   container_name: target-writer2
  #   image: slotix/dbs-target-writer
  #   entrypoint:
  #     - ./dbs-target-writer
  #     - --host=dbs-target-writer2:8023  
  #     - --nats=nats:4222
  #     - --prometheus=http://prometheus:9090
  #   ports:
  #     - 8023:8023
  #   depends_on:
  #     - dbs-api


  # dbs-target-writer3:
  #   container_name: target-writer3
  #   image: slotix/dbs-target-writer
  #   entrypoint:
  #     - ./dbs-target-writer
  #     - --host=dbs-target-writer3:8024  
  #     - --nats=nats:4222
  #     - --prometheus=http://prometheus:9090
  #   ports:
  #     - 8024:8024
  #   depends_on:
  #     - dbs-api

  nats:
    container_name: nats
    image: nats
    entrypoint: /nats-server
    command: "--jetstream -m 8222 --store_dir /data/nats-server"
    ports:
      - 4222:4222
      - 8222:8222
    # volumes:
    #   - ./_storage/nats:/data/nats-server/jetstream

  prometheus:
    image: slotix/dbs-prometheus:latest
    container_name: prom
    user: root
    ports:
      - 9090:9090

```
